### PR TITLE
Second pass of missing strings from `pt-pt`

### PR DESCRIPTION
**Pull request by petecooper**
Same translator as https://github.com/textpattern/textpacks/pull/101 - translations appear sound in Google Translate. One clarification, too - line 1157.

### CODE REVIEW

**Comment by philwareham** [comment]
Hey Pete, do you want repo access to do merges yourself?

**Comment by petecooper** [comment]
Sure thing, why not. It'll save the tooling around with fork/modify/commit/pull request/delete fork *and* save you some time.

**Comment by philwareham** [comment]
Welcome aboard! I've also added you to the documentation team - lucky you! I'll be onto documentation stuff after the RPC fixup.

**Comment by petecooper** [comment]
Much excite. Very wow.

**Pull request merged**
