### PR TITLE
Append `path` to `img_dir` for 3x English packs

### PR DESCRIPTION
**Pull request by petecooper**
Resolves disparity between strings when Diagnostics reports non-writable directories:

```
Image directory is not writable: /var/www/vhosts/textpattern.github/dev/images
File directory path is not writable: /var/www/vhosts/textpattern.github/dev/files 
```

### CODE REVIEW

**Comment by philwareham** [comment]
Not sure about this. It *is* technically a path but unlike the other path fields in prefs it's relative and not absolute. I have no idea why that would be, but it is. Maybe @rwetzlmayr or @Bloke can shed light on the history of that.

**Comment by petecooper** [comment]
Thanks, @philwareham. I'm nitpicking while I run through a fresh 4.7-dev install, no biggie if this is too trivial.

**Comment by petecooper** [comment]
Follow up: if the warning is thrown on Content -> Images or Content -> Files, no reference to `path` appears, so a potential solution would be to undo the changes made so far, and zap the reference to `path` in the files directory gTxt instead.

…or just leave it alone and close the issue. That's totally OK.

**Comment by petecooper** [comment]
Alright, I'll close this PR and rework it so there's consistency. More delving needed, first.

Thanks, both.

**Pull request closed without merging**
