### PR TITLE
Add some missing strings to European languages

### PR DESCRIPTION
**Pull request by petecooper**

### CODE REVIEW

**Comment by philwareham** [comment]
Cheers. I think the invalid_postdate strings need a full stop at the end. So if you add that I will merge this.

Was fixing up the Bahasa Indonesia language in RPC this morning. That is a messy one - about half the strings aren't even created in that part of the database, let alone translated. :(

**Comment by petecooper** [comment]
Full stop = done. Anything in RPC you can farm out to me, @philwareham?

**Comment by philwareham** [comment]
@petecooper thanks. The RPC work is a one-person job really. I compare the Textpack strings against ones I've exported from the RPC database then amend in RPC to match. It's painful but I've done half the languages now and am in a routine. Cheers anyway.

**Comment by petecooper** [comment]
No worries. I'll plug away with the missing Textpack strings.

**Pull request merged**
