### PR TITLE
Add `invalid_timestamp` string

### PR DESCRIPTION
**Pull request by petecooper**
Addresses: http://forum.textpattern.com/viewtopic.php?id=37577 and
http://forum.textpattern.com/viewtopic.php?id=45859

### CODE REVIEW

**Comment by petecooper** [comment]
Travis failed due to an extra `=>` in one of the `el-gr.textpack` strings. Sorry, Greeks.

**Comment by philwareham** [comment]
This is probably missing in RPC server too as that is where original Textpacks came from pre-GitHub repo.

**Comment by petecooper** [comment]
@philwareham - shall I scrap this and re-submit as a single commit to get around the merge conflicts?

**Comment by philwareham** [comment]
Hi. OK, if you don't mind.

**Pull request closed without merging**
