### PR TITLE
Update ja-jp.textpack

### PR DESCRIPTION
**Pull request by new3kinnnn**
added missing strings and small changes

### CODE REVIEW

**Comment by petecooper** [comment]
Hey @new3kinnnn - great work, thank you! Would you be OK to be listed as a Textpattern translator here?: http://forum.textpattern.com/viewtopic.php?id=45789

**Comment by new3kinnnn** [comment]
@petecooper - ofcourse yes :)
My forum ID on textpattern is 70383 http://forum.textpattern.com/profile.php?id=70383

**Comment by petecooper** [comment]
@new3kinnnn - perfect! Thank you _very_ much.

**Comment by philwareham** [comment]
Thanks!

**Pull request merged**
