### PR TITLE
Update fr-fr.textpack

### PR DESCRIPTION
**Pull request by cara-tm**
Latest translations.

### CODE REVIEW

**Comment by philwareham** [comment]
Thanks as ever Patrick!

**Comment by cara-tm** [comment]
My pleasure ;)

**Comment by philwareham** [comment]
Hi again Patrick - there is one more translation needed:

extension => Extension

As in file extension (used in the image list search widget).

**Comment by cara-tm** [comment]
Yep! Perfect (as always ;) )

**Pull request merged**
