### PR TITLE
Update fr.txt

### PR DESCRIPTION
**Pull request by cara-tm**
Last tentative to remove the encoded space before the last sign as asked by the French community (translation from the Crowdin website has been updated too).

### CODE REVIEW

**Comment by philwareham** [comment]
So is this a non-breaking space?

**Comment by cara-tm** [comment]
It seems there was an old `&nbsp;` and some users notice me (even if I do not encounter this problem within 4.6.2 or 4.7.x).
This annoying behaviour only affects the javascript message.
I often use non-breaking spaces for long sentences in responsive context. So in this case, I think we can safely delete it without any problems in order to definitly close this issue.

**Comment by philwareham** [comment]
OK, makes sense now, thanks.

**Comment by cara-tm** [comment]
Feedback received by email: "Perfect!"

**Pull request merged**
