### PR TITLE
Update fr-fr.textpack

### PR DESCRIPTION
**Pull request by cara-tm**
Translate "installing_language".

### CODE REVIEW

**Comment by philwareham** [comment]
Thanks! When I next refresh RPC I will add this string in.

**Comment by petecooper** [comment]
Bonjour @cara-tm - are you OK if I add you to the list [here](http://forum.textpattern.com/viewtopic.php?pid=291807#p291807) as a Textpack translator? Your previous translation work is excellent, and I your services are valuable. Thanks in advance.

**Comment by cara-tm** [comment]
Yep sure! You can add me (Pat) as a French Translator: I charge myself for some years, now.

**Comment by petecooper** [comment]
Thank you, sir.

**Comment by cara-tm** [comment]
;)

**Pull request merged**
