### PR TITLE
Update de-de.textpack

### PR DESCRIPTION
**Pull request by eliph**
older and newer should both be capitalised in German

### CODE REVIEW

**Comment by eliph** [comment]
small changes

**Comment by eliph** [comment]
small changes regarding capitalisation and slogan

**Comment by philwareham** [comment]
Thanks!

**Comment by eliph** [comment]
Please revert. It breaks my newly created website that is based on a fresh installation of 4.6dev, and a 404 error page is thrown when pointing to a category page. No such problem with English (Great Britain).

**Comment by Bloke** [comment]
Sorry, didn't spot this or I'd have chimed in. The *_context entries MUST remain lower case for URL consistency. They are used in landing pages to designate context:

    example.org/kategorie/bild/my-image-category

As you have it right now, the URL would need to be constructed thus:

    example.org/kategorie/Bildkontext/my-image-category

I'm wondering if permitting multi-lingual URLs was a bad move... :-|

**Comment by philwareham** [comment]
Partially reverted - I've restored to the previous *_context entries for this, which are in English, but I guess that is OK?

**Comment by Bloke** [comment]
Yeah that's fine. It just means that any time the context is used in URLs, those words must appear in English.

I vaguely remember documenting this somewhere, but can't for the life of me remember where.

**Comment by eliph** [comment]
Actually, my site was broken after I had installed the German language update that I had proposed a couple of days ago, and I got 404 pages for no apparent reasons. But now it works again. Thanks!

**Comment by philwareham** [comment]
I'm a little confused... Do the *_context strings break existing URLs in people's sites. Or are they ok to translate/change?

**Comment by eliph** [comment]
In my case URLs with "&context=image" did no longer work. But it may be my fault, because URL snippets containing "&context=image" are hard wired in Textpattern forms.

**Comment by Bloke** [comment]
Yes, they'll break things in people's sites. In exactly the same way as altering the:
* `section`
* `category`
* `author`
* `file_download`

strings will do. The context works the same way as those: it's run through `gTxt()`.

There is, however, a bug that I've been meaning to fix for ages. The context values in function `validContext()` should be run through `urldecode(strtolower(urlencode()))` in the same way that the strings in the list above are. That would (at least) prevent any capitalisation or non-url-safe characters in translated strings from breaking site URLs.

**Comment by Bloke** [comment]
@eliph Not your fault. It relates to the behaviour I just mentioned. When the strings were changed from `image` to `Image` (well, the equivalent strings in German), the URLs break.

That needs to be changed in core to be independent of case. Because you are quite correct that the nouns in German should have capital letter in the translated strings to comply with grammar rules.

**Comment by Bloke** [comment]
The upshot of all this of course, is that the site URLs that use the predefined route strings for any languages that do not currently have translations for any of the above listed strings (or the `context_` strings) will break when those strings are added to that language pack.

To date, authors of sites using languages without the translated strings will have been using the English names `category`, `section` and so forth when building their site structure. Inventive solutions to this wold be most welcome, but I can't think of one off the top of my head.

**Comment by eliph** [comment]
Why offer translating these "predefined route strings" in textpacks then anyway? I have no problem with a german web site that has "image" or "category" in its URLs. Translating strings is a great thing with regard to the administrative interface, but should not affect internal constructs, such as the software logic, Textpattern Tags or URLs imho.

**Comment by philwareham** [comment]
Ok, please resubmit a commit with the contexts translated but in lowercase and I will merge and then put in RPC. Best to have them translated I think.

**Comment by Bloke** [comment]
@eliph Yeah, I'm not sure how best to manage it. We want stuff to be localised, but don't want to break URLs when things are altered. Would rather not "hard code" such translated strings into core that are vital to the success of a website, even if it meant the end of such 404s. Any ideas on this welcome.

**Comment by philwareham** [comment]
This needs to be noted somewhere in the repo documentation. I had no idea about this so probably most translators didn't know either.

Although have something in language packs that directly affects urls is not a great design choice, I'd rather translate and be done with it. What do you think?

**Comment by Bloke** [comment]
Yes, if we can get these "special" strings translated across the board then that'd be grand, with a suitable note in the readme/history to the effect that the URLs for any manually-constructed links to such pages will have to change accordingly.

Anything that comes from a built-in tag will (ahem, should) automatically update to reflect the translated structure, but that would need to be verified.

Let's go for lower-case strings for now until someone (probably me) gets round to fixing the case-sensitive nature of `validContext()`. Once that's done we can alter the case of strings on a lang-by-lang basis if necessary.

Regarding the design decision, yeah, the context thing just followed in the footsteps of what went before. Going forward, we have some options:

1. Force English for everyone (`example.de/category/image/das-pferd`). This affects every language with current strings that have translations for those strings.
2. Stick with what we have, but lower-case the strings in core (`example.de/kategorie/bild/das-pferd`). Nicer for international users, with the caveat that the strings should never change. Assuming all languages are translated, this affects all installs that don't currently have a translation for those strings.
3. Permit both forms, but find a way to deliver a 404 on the English format if an international translation exists, so that duplicate content SEO badness is avoided. This affects the same group as option 2, but I've no idea how to implement it.
4. Hard-code the special strings elsewhere, or otherwise indicate their special nature in the Textpacks. Perhaps these could be translated somewhere other than the main Textpack, by pulling them out into special files that are "included" by default in that language's main Textpack? Just some way of separating them so they don't get trampled by mistake.
5. A preference setting to control how URL generation is handled: "Internationalised" or "English". It would default to Internationalised, but that gives site authors a fallback to retain the current English behaviour of their site if their language has the special strings translated prior to release. Quite a bit of work to retrofit `preText()` and make all the relevant tags aware of the setting so they can render the appropriate URLs, but may be worth considering. This might also be handy for languages that struggle with the RFC for international characters in URLs, or that might otherwise be impacted (are there any? Not sure). I'm presuming that the 'category' string, for example, is used in a few places around the admin-side too, so to be able to see it in the local language there but in English in front side URLs might be desirable? Not sure.
6. Something else...?

Also, we need to be careful not to trample old installs via changes to these strings on RPC.

**Comment by eliph** [comment]
To me, the language setting is nothing that is fixed or forever on a given web site. There may be several good reasons for changing between languages, even frequently. There may be an english-speaking guy developing or editing some content or design for a German website, or you switch to English for some time to more easily follow the documentation, or you would want to show off the backend to somebody from Spain or China. If such actions would unwillingly make certain parts of your website inaccessible, break external links, or just cause confusion, then this would be good reasons for keeping the URLs constant, that is in the English language. The native language of who is using the backend not necessarily is the same as who is using the frontend. And who cares about the language in URLs anyway? Therefore, I would vote for option 1.

The next best option is #4 in my opinion, but a lot of programming work may be needed, and even more for the other options. The fact that up to now there seem to be no real complaints for this matter, despite the fact that Textpattern is quite an international CMS, makes me think that this is not a terribly important topic, and resources, that are very limited in terms of manpower, would better be directed to other more burning problems.

**Comment by Bloke** [comment]
@eliph You know, that's quite a compelling argument. I hadn't thought about the impact of changing admin side language on the URLs. That's something we want to avoid in a multi-lingual admin/public environment (which I'm planning to do).

Forcing special URL params to non-translatable English strings is fine by me if everyone agrees. It's a backwards-compatibility issue for sure.

I wonder if there are any compelling reasons from the international community for using localised strings in URLs. Aside from it looking better, of course.

Any other CMSs we can look at to see how they handle this?

**Comment by eliph** [comment]
Don't know much (if anything) about other CMS, but Moodle, which is very popular in worldwide, does not care about internationalization of URL strings. See: https://moodle.org/demo/. You can log in as admin and chose some language (including "de for kids"), but the URLs would remain in English.

**Pull request merged**
